services:
  store_manager_app:
    build: .
    container_name: store_manager_app
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks: [appnet]
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks: [appnet]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uuser", "-ppass"]
      interval: 5s
      timeout: 3s
      retries: 20

  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo-data:/data/db
    networks: [appnet]
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet -u user -p pass --eval \"db.adminCommand('ping')\" || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

networks:
  appnet:
    driver: bridge

volumes:
  mongo-data:
