name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: labo01

    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Creer fichier .env
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_NAME=mydb" >> .env
          echo "DB_USERNAME=user" >> .env
          echo "DB_PASSWORD=pass" >> .env
      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Exécuter docker-compose
        run: docker compose up -d
      - name: Wait for DB to be ready
        run: |
          until docker exec db pg_isready -U testuser; do sleep 1; done
      - name: Exécuter les tests
        working-directory: src
        run: echo "python3 -m pytest"

